spring:
  datasource:
    url: jdbc:mysql://localhost/my_db?useSSL=false&serverTimezone=UTC
    username: bestuser
    password: bestuser
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  aop:
    auto: true
server:
  port: 9090
  servlet:
    context-path: /api
logging:
  file:
    name: log.txt
  pattern:
    file: "%msg%n"
